# Generated by Django 5.2.4 on 2025-07-10 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_department_name_alter_municipality_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalityContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('historia', 'Historia'), ('gastronomia', 'Gastronomía'), ('turismo', 'Turismo')], max_length=20)),
                ('content', models.TextField(help_text='Contenido en formato HTML')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='page.municipality')),
            ],
            options={
                'unique_together': {('municipality', 'category')},
            },
        ),
    ]
