# Generated by Django 5.2.4 on 2025-08-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/events/', verbose_name='Imagen Principal'),
        ),
    ]
