# Generated by Django 5.2.4 on 2025-07-18 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_municipalitycontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='sin nombre', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='municipality',
            name='name',
            field=models.CharField(default='sin nombre', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Contenido en formato HTML')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='page.category')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='page.municipality')),
            ],
        ),
        migrations.DeleteModel(
            name='MunicipalityContent',
        ),
        migrations.AddConstraint(
            model_name='content',
            constraint=models.UniqueConstraint(fields=('municipality', 'category'), name='unique_municipality_category'),
        ),
    ]
