# Generated by Django 5.2.4 on 2025-07-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_category_department_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
