# Generated by Django 5.2.4 on 2025-08-05 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_event_date_alter_event_municipality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, help_text='Versión del nombre para URLs amigables.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría del Ítem',
                'verbose_name_plural': 'Categorías de Ítems',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contentitem',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='schedule',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Horario'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='page.categoryitem', verbose_name='Categoría del Ítem'),
            preserve_default=False,
        ),
    ]
