# Generated by Django 5.2.4 on 2025-07-24 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_municipality_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ['department__name', 'name'], 'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Versión del nombre para URLs amigables.', max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, help_text='Versión del nombre para URLs amigables.', max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='slug',
            field=models.SlugField(blank=True, help_text='Versión del nombre para URLs amigables. Se genera automáticamente.', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='page.department', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='municipality',
            unique_together={('name', 'department')},
        ),
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(blank=True, help_text='Contenido principal para la página de esta categoría en el municipio.', verbose_name='Contenido Introductorio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipality_pages', to='page.category', verbose_name='Categoría')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_pages', to='page.municipality', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Página de Categoría',
                'verbose_name_plural': 'Páginas de Categoría',
                'ordering': ['municipality__name', 'category__name'],
                'unique_together': {('municipality', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, help_text='Se genera automáticamente para la URL.', max_length=220, unique=True)),
                ('summary', models.TextField(help_text='Texto corto para mostrar en las listas.', verbose_name='Resumen')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content_items/images/', verbose_name='Imagen Principal')),
                ('body', models.TextField(help_text='El contenido detallado para la página del ítem.', verbose_name='Cuerpo del Contenido')),
                ('published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='page.categorypage', verbose_name='Página de Categoría')),
            ],
            options={
                'verbose_name': 'Ítem de Contenido',
                'verbose_name_plural': 'Ítems de Contenido',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
