# Generated by Django 5.2.4 on 2025-08-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_remove_category_description_municipalityimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipalityimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/', verbose_name='Imagen Municipio'),
        ),
    ]
