# Generated by Django 5.2.4 on 2025-08-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_alter_municipalityimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipalityimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/municipalities/', verbose_name='Imagen Municipio'),
        ),
    ]
